### ISSUE TITLE
where is /maps/lofi_char.png and so on??

### ISSUE THREAD

**Issue by exe19890522** [riicchhaarrd/webrpg#1]
i had run the server and client(debug),but it show me:
maps/lofi_obj.png 404 (Not Found)==i use other img instead
 maps/lofi_char.png 404 (Not Found)==i use other img instead
maps/test.json 404 (Not Found)==========this one i don't know how to do with it.
did you still on this ?

**Comment by riicchhaarrd** [comment]
The sprites belong to https://www.oryxdesignlab.com/sprites
For the .json file, it follows the map format exported by the Tiled editor (https://www.mapeditor.org/).

You could replace the sprite pack by adjusting the x,y offsets in the code and using a different tileset.
